package com.tec.quote;

public class RandomQuote {
    String[] quotes = {
            "Believe you can and you're halfway there.",
            "Your time is limited, so don’t waste it living someone else’s life.",
            "Success is not final, failure is not fatal: it is the courage to continue that counts.",
            "Do what you can, with what you have, where you are.",
            "Hardships often prepare ordinary people for an extraordinary destiny.",
            "Success usually comes to those who are too busy to be looking for it.",
            "Don’t watch the clock; do what it does. Keep going.",
            "The only way to do great work is to love what you do.",
            "It always seems impossible until it's done.",
            "Dream big and dare to fail.",
            "Start where you are. Use what you have. Do what you can.",
            "You miss 100% of the shots you don’t take.",
            "Stay hungry, stay foolish.",
            "The best way to predict your future is to create it.",
            "Strive not to be a success, but rather to be of value.",
            "Failure will never overtake me if my determination to succeed is strong enough.",
            "The harder you work for something, the greater you'll feel when you achieve it.",
            "Don’t be afraid to give up the good to go for the great.",
            "I never dreamed about success. I worked for it.",
            "Push yourself, because no one else is going to do it for you.",
            "Great things never come from comfort zones.",
            "Success doesn’t just find you. You have to go out and get it.",
            "Dream it. Wish it. Do it.",
            "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
            "The key to success is to focus on goals, not obstacles.",
            "Don’t stop when you’re tired. Stop when you’re done.",
            "Little things make big days.",
            "The only limit to our realization of tomorrow is our doubts of today.",
            "If you want to achieve greatness stop asking for permission.",
            "Do something today that your future self will thank you for.",
            "It’s going to be hard, but hard does not mean impossible.",
            "Wake up with determination. Go to bed with satisfaction.",
            "Success is what comes after you stop making excuses.",
            "The difference between ordinary and extraordinary is that little extra.",
            "Believe in yourself. You are braver than you think.",
            "Action is the foundational key to all success.",
            "Don’t limit your challenges. Challenge your limits.",
            "If it doesn’t challenge you, it won’t change you.",
            "Work hard in silence, let success make the noise.",
            "Doubt kills more dreams than failure ever will.",
            "Don’t wait for opportunity. Create it.",
            "If you can dream it, you can do it.",
            "Go the extra mile. It’s never crowded.",
            "Be stronger than your excuses.",
            "A little progress each day adds up to big results.",
            "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
            "The way to get started is to quit talking and begin doing.",
            "You don’t have to be great to start, but you have to start to be great.",
            "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
            "Work until your idols become your rivals.",
            "Discipline is the bridge between goals and accomplishment.",
            "I am not a product of my circumstances. I am a product of my decisions.",
            "We generate fears while we sit. We overcome them by action.",
            "Don’t wish it were easier. Wish you were better.",
            "Try not to become a man of success, but rather try to become a man of value.",
            "Setting goals is the first step in turning the invisible into the visible.",
            "The future depends on what you do today.",
            "Opportunities don't happen. You create them.",
            "The best revenge is massive success.",
            "Learn as if you will live forever, live like you will die tomorrow.",
            "Knowing is not enough; we must apply. Wishing is not enough; we must do.",
            "The successful warrior is the average man, with laser-like focus.",
            "Success is walking from failure to failure with no loss of enthusiasm.",
            "If you are not willing to risk the usual, you will have to settle for the ordinary.",
            "You don’t need to see the whole staircase, just take the first step.",
            "Success is getting what you want. Happiness is wanting what you get.",
            "Live as if you were to die tomorrow. Learn as if you were to live forever.",
            "Don’t let yesterday take up too much of today.",
            "We may encounter many defeats but we must not be defeated.",
            "In the middle of difficulty lies opportunity.",
            "Either you run the day or the day runs you.",
            "Keep your face always toward the sunshine—and shadows will fall behind you.",
            "You are never too old to set another goal or to dream a new dream.",
            "Perseverance is not a long race; it is many short races one after the other.",
            "Big journeys begin with small steps.",
            "Be so good they can’t ignore you.",
            "Start each day with a positive thought and a grateful heart.",
            "Don’t count the days, make the days count.",
            "Success is the sum of small efforts repeated day in and day out.",
            "Act as if what you do makes a difference. It does.",
            "Do not wait to strike till the iron is hot; but make it hot by striking.",
            "Energy and persistence conquer all things.",
            "Nothing will work unless you do.",
            "The only place where success comes before work is in the dictionary.",
            "Don’t raise your voice, improve your argument.",
            "There are no shortcuts to any place worth going.",
            "You can if you think you can.",
            "Be the change that you wish to see in the world.",
            "Success is not how high you have climbed, but how you make a positive difference to the world.",
            "You only live once, but if you do it right, once is enough.",
            "I find that the harder I work, the more luck I seem to have.",
            "The secret of getting ahead is getting started.",
            "There is no elevator to success — you have to take the stairs.",
            "You don’t find will power, you create it.",
            "Don’t ruin a good today by thinking about a bad yesterday.",
            "Some people dream of success, while other people get up every morning and make it happen.",
            "You don’t grow when things are easy. You grow when you face challenges.",
            "Hustle in silence and let your success make the noise.",
            "It’s not whether you get knocked down, it’s whether you get up.",
            "Stay away from those people who try to disparage your ambitions.",
            "Success means doing the best we can with what we have.",
            "One day or day one. You decide.",
            "Don't fear failure. Fear being in the exact same place next year as you are today."
    };

    public String getQuote(){
        return quotes[(int) (Math.random()*100)];
    }

}
